# Imagen oficial de Bun
FROM oven/bun:latest

# Crear directorio de trabajo y dar permisos a bun
RUN mkdir -p /app && chown -R bun:bun /app

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Cambiar al usuario existente 'bun'
USER bun

# Copiar package.json y lockfile primero
COPY --chown=bun:bun package*.json bun.lockb* ./

# Instalar dependencias
RUN bun install

# Copiar todo el código al contenedor
COPY --chown=bun:bun . .

# Exponer el puerto del dev server (por si luego lo querés levantar manualmente)
EXPOSE 5173

# Mantener el contenedor corriendo sin iniciar el dev server
CMD ["tail", "-f", "/dev/null"]
