FROM oven/bun:1.2.22-alpine

RUN apk add --no-cache bash

# Crear directorio de trabajo y dar permisos a bun
RUN mkdir -p /app && chown -R bun:bun /app

WORKDIR /app

USER bun

# Copiar package.json y lockfile primero
COPY --chown=bun:bun package.json bun.lock ./

RUN bun install

EXPOSE 5173

CMD ["tail", "-f", "/dev/null"]
