services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: cochera-frontend:latest
    container_name: cochera-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    restart: unless-stopped
    stdin_open: true
    tty: true

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    image: cochera-api:latest
    container_name: cochera-api
    ports:
      - "5000:5000"
      - "5500:5500"
    volumes:
      - .:/home/devuser/app
      - ${SSH_AUTH_SOCK}:/ssh-agent
      - go_mod_cache:/home/devuser/go/pkg/mod
      - go_build_cache:/home/devuser/.cache/go-build
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
      - DEV_DB_URL=postgres://postgres:example@dev_db:5432/dev_db?sslmode=disable
      - TEST_DB_URL=postgres://postgres:example@test_db:5432/test_db?sslmode=disable
    depends_on:
      - dev_db
      - test_db
    stdin_open: true
    tty: true

  dev_db:
    image: postgres:17.5
    container_name: cochera-dev-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: dev_db
    ports:
      - "5433:5432"
    volumes:
      - api_data:/var/lib/postgresql/data
  
  test_db:
    image: postgres:17.5
    container_name: cochera-test-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: test_db
    ports:
      - "5434:5432"

volumes:
  api_data:
  frontend_node_modules:
  go_mod_cache:
  go_build_cache:

networks:
  default:
    name: localdev
