FROM golang:1.25.1-alpine3.22

# Argumentos para el usuario no-root
ARG USERNAME=devuser
ARG USER_UID=1000
ARG USER_GID=1000

# Instalar sudo y crear usuario/grupo (Alpine syntax)
RUN apk add --no-cache curl sudo make bash git openssh-client && \
    addgroup -g $USER_GID $USERNAME && \
    adduser -u $USER_UID -G $USERNAME -D -s /bin/sh $USERNAME && \
    echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/$USERNAME

USER $USERNAME

# Crear directorio de trabajo y variables de entorno
RUN mkdir -p /home/$USERNAME/app
WORKDIR /home/$USERNAME/app
ENV GOPATH=/home/$USERNAME/go
ENV PATH=$GOPATH/bin:$PATH
RUN mkdir -p $GOPATH/bin

ARG MIGRATE_VERSION=v4.18.1
ARG GOLANGCI_LINT_VERSION=v2.4.0

# Instalar migrate
RUN curl -L https://github.com/golang-migrate/migrate/releases/download/$MIGRATE_VERSION/migrate.linux-amd64.tar.gz | \
    tar xvz && \
    chmod +x migrate && \
    mv migrate $GOPATH/bin/migrate

# Instalar golangci-lint
RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | \
    sh -s -- -b $GOPATH/bin $GOLANGCI_LINT_VERSION

COPY --chown=$USERNAME:$USERNAME go.mod go.sum ./
RUN go mod tidy

COPY --chown=$USERNAME:$USERNAME . .

EXPOSE 5000

CMD ["tail", "-f", "/dev/null"]