FROM golang:1.25.1-alpine3.22

# Argumentos para el usuario no-root
ARG USERNAME=devuser
ARG USER_UID=1000
ARG USER_GID=1000

# Instalar sudo y crear usuario/grupo (Alpine syntax)
RUN apk add --no-cache curl sudo make bash git openssh-client && \
    addgroup -g $USER_GID $USERNAME && \
    adduser -u $USER_UID -G $USERNAME -D -s /bin/bash $USERNAME && \
    echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/$USERNAME

USER $USERNAME

# Crear directorio de trabajo y variables de entorno
ENV TERM=xterm-256color
RUN mkdir -p /home/$USERNAME/app
WORKDIR /home/$USERNAME/app
ENV GOPATH=/home/$USERNAME/go
ENV PATH=$GOPATH/bin:$PATH
RUN mkdir -p /home/$USERNAME/.cache/go-build

ARG MIGRATE_VERSION=v4.18.1
ARG GOLANGCI_LINT_VERSION=v2.4.0

# Instalar migrate
RUN curl -L https://github.com/golang-migrate/migrate/releases/download/$MIGRATE_VERSION/migrate.linux-amd64.tar.gz | \
    sudo tar xz -C /usr/local/bin && \
    sudo chmod +x /usr/local/bin/migrate

# Instalar golangci-lint
RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | \
    sudo sh -s -- -b /usr/local/bin $GOLANGCI_LINT_VERSION

COPY --chown=$USERNAME:$USERNAME go.mod go.sum ./
RUN go mod download

EXPOSE 5000

CMD ["tail", "-f", "/dev/null"]