version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: cochera-api:latest
    container_name: cochera-api
    ports:
      - "5000:5000"
      - "5500:5500"
    volumes:
      - .:/api
    depends_on:
      - dev_db
      - test_db
    command: tail -f /dev/null

  dev_db:
    image: postgres:17.5
    container_name: cochera-dev-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: dev_db
    ports:
      - "5433:5432"
    volumes:
      - api_data:/var/lib/postgresql/data
  
  test_db:
    image: postgres:17.5
    container_name: cochera-test-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: test_db
    ports:
      - "5434:5432"

volumes:
  api_data:

networks:
  default:
    name: localdev
