package myerrors

import "errors"

var (
	ErrRequiredDNI                 = errors.New("dni is required")
	ErrDNIMustBeNumber             = errors.New("dni must be a positive integer")
	ErrDuplicateDNI                = errors.New("dni already exists")
	ErrRequiredName                = errors.New("name is required")
	ErrNameMustBeString            = errors.New("name must be a string")
	ErrInvalidName                 = errors.New("name must be a string")
	ErrNameTooLong                 = errors.New("name must be 50 characters long at max")
	ErrInvalidLastName             = errors.New("last name must be a string")
	ErrRequiredLastName            = errors.New("last name is required")
	ErrLastNameMustBeString        = errors.New("last name must be a string")
	ErrLastNameTooLong             = errors.New("last name must be 50 characters long at max")
	ErrInvalidAddress              = errors.New("address must be a string")
	ErrRequiredAddress             = errors.New("address is required")
	ErrAddressMustBeString         = errors.New("address must be a string")
	ErrAddressTooLong              = errors.New("address must be 100 characters long at max")
	ErrInvalidPhone                = errors.New("phone must be a string")
	ErrRequiredPhone               = errors.New("phone is required")
	ErrPhoneMustBeString           = errors.New("phone must be a string")
	ErrPhoneMustStartWithPlusSign  = errors.New("phone must start with + sign")
	ErrPhoneMustContainNumbersOnly = errors.New("phone must contain numbers only")
	ErrPhoneTooLong                = errors.New("phone must have 15 digits max")
	ErrPhoneFullOfZeroes           = errors.New("phone cannot be full of zeroes")
	ErrInvalidEmail                = errors.New("email must be a string")
	ErrDuplicateEmail              = errors.New("email already in use")
	ErrRequiredEmail               = errors.New("email is required")
	ErrEmailMustBeString           = errors.New("email must be a string")
	ErrInvalidEmailFormat          = errors.New("email must follow standard format")
	ErrEmailTooLong                = errors.New("email must be 100 characters long at max")
	ErrRequiredEntryMonth          = errors.New("entry month is required")
	ErrEntryMonthMustBeString      = errors.New("entry month must be string")
	ErrEntryMonthInvalidFormat     = errors.New("entry month must have this format: MM-YYYY")
	ErrTenantNotFound              = errors.New("tenant not found")
)
