package domain

import "errors"

var (
	ErrRequiredDNI                 = errors.New("el DNI es obligatorio")
	ErrDNIMustBeNumber             = errors.New("el DNI debe ser un entero positivo")
	ErrDuplicateDNI                = errors.New("el DNI ya existe")
	ErrRequiredName                = errors.New("el nombre es obligatorio")
	ErrNameMustBeString            = errors.New("el nombre debe ser un string")
	ErrInvalidName                 = errors.New("el nombre debe ser un string")
	ErrInvalidLastName             = errors.New("el apellido debe ser un string")
	ErrRequiredLastName            = errors.New("el apellido es obligatorio")
	ErrLastNameMustBeString        = errors.New("el apellido debe ser un string")
	ErrLastNameTooLong             = errors.New("el apellido debe tener 50 caracteres como máximo")
	ErrInvalidAddress              = errors.New("el domicilio debe ser un string")
	ErrRequiredAddress             = errors.New("el domicilio es obligatorio")
	ErrInvalidPhone                = errors.New("el teléfono debe ser un string")
	ErrRequiredPhone               = errors.New("el teléfono es obligatorio")
	ErrPhoneMustBeString           = errors.New("el teléfono debe ser un string")
	ErrPhoneMustContainNumbersOnly = errors.New("el teléfono solo puede tener números")
	ErrPhoneFullOfZeroes           = errors.New("el teléfono no puede estar lleno de ceros")
	ErrInvalidEmail                = errors.New("el email debe ser un string")
	ErrDuplicateEmail              = errors.New("el email ya está en uso")
	ErrRequiredEmail               = errors.New("el email es obligatorio")
	ErrEmailMustBeString           = errors.New("el email debe ser un string")
	ErrInvalidEmailFormat          = errors.New("el email debe seguir el formato estándar")
	ErrEmailTooLong                = errors.New("el email debe tener 100 caracteres como máximo")
	ErrRequiredEntryMonth          = errors.New("el mes de ingreso es obligatorio")
	ErrEntryMonthMustBeString      = errors.New("el mes de ingreso debe ser un string")
	ErrEntryMonthInvalidFormat     = errors.New("el mes de ingreso debe seguir este formato: MM-YYYY")
	ErrTenantNotFound              = errors.New("inquilino no encontrado")
	ErrNoTenantsCreated            = errors.New("no hay inquilinos registrados")
	ErrNoMatchingTenantsFound      = errors.New("no se encontraron inquilinos que coincidan")
)
