package domain

import "errors"

var (
	ErrRequiredDNI                 = errors.New("El DNI es obligatorio")
	ErrDNIMustBeNumber             = errors.New("El DNI debe ser un entero positivo")
	ErrDuplicateDNI                = errors.New("El DNI ya existe")
	ErrRequiredName                = errors.New("El nombre es obligatorio")
	ErrNameMustBeString            = errors.New("El nombre debe ser un string")
	ErrInvalidName                 = errors.New("El nombre debe ser un string")
	ErrNameTooLong                 = errors.New("El nombre debe tener 50 caracteres como máximo")
	ErrInvalidLastName             = errors.New("El apellido debe ser un string")
	ErrRequiredLastName            = errors.New("El apellido es obligatorio")
	ErrLastNameMustBeString        = errors.New("El apellido debe ser un string")
	ErrLastNameTooLong             = errors.New("El apellido debe tener 50 caracteres como máximo")
	ErrInvalidAddress              = errors.New("El domicilio debe ser un string")
	ErrRequiredAddress             = errors.New("El domicilio es obligatorio")
	ErrAddressMustBeString         = errors.New("El domicilio debe ser un string")
	ErrAddressTooLong              = errors.New("El domicilio debe tener 100 caracteres como máximo")
	ErrInvalidPhone                = errors.New("El teléfono debe ser un string")
	ErrRequiredPhone               = errors.New("El teléfono es obligatorio")
	ErrPhoneMustBeString           = errors.New("El teléfono debe ser un string")
	ErrPhoneMustStartWithPlusSign  = errors.New("El teléfono debe comenzar con un símbolo de +")
	ErrPhoneMustContainNumbersOnly = errors.New("El teléfono solo puede tener números")
	ErrPhoneTooLong                = errors.New("El teléfono debe tener 15 dígitos como máximo")
	ErrPhoneFullOfZeroes           = errors.New("El teléfono no puede estar lleno de ceros")
	ErrInvalidEmail                = errors.New("El email debe ser un string")
	ErrDuplicateEmail              = errors.New("El email ya está en uso")
	ErrRequiredEmail               = errors.New("El email es obligatorio")
	ErrEmailMustBeString           = errors.New("El email debe ser un string")
	ErrInvalidEmailFormat          = errors.New("El email debe seguir el formato estándar")
	ErrEmailTooLong                = errors.New("El email debe tener 100 caracteres como máximo")
	ErrRequiredEntryMonth          = errors.New("El mes de ingreso es obligatorio")
	ErrEntryMonthMustBeString      = errors.New("El mes de ingreso debe ser un string")
	ErrEntryMonthInvalidFormat     = errors.New("El mes de ingreso debe seguir este formato: MM-YYYY")
	ErrTenantNotFound              = errors.New("Inquilino no encontrado")
	ErrNoTenantsCreated            = errors.New("No hay inquilinos registrados")
	ErrNoMatchingTenantsFound      = errors.New("No se encontraron inquilinos que coincidan")
)
